// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nokyneehdbmyrjmpvneu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5va3luZWVoZGJteXJqbXB2bmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDQxMTUsImV4cCI6MjA3MzUyMDExNX0.cpZ9ruEqfRb5p3kCksePUzlOfpCAmhSq3gIcdnznTkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});